### ISSUE TITLE
Add Travis Badge in README

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/git-profiler-bot#22]
@gurungrahul2 Please complete it as part of previous bounty

**Comment by gurungrahul2** [comment]
sure.

**Comment by gurungrahul2** [comment]
you will see a PR before Xmas.

**Comment by aashutoshrathi** [comment]
It's just one line of code, can you do it ASAP. :sweat_smile:

**Comment by gurungrahul2** [comment]
by travis batch you mean build status of repo?
