### ISSUE TITLE
Tests are failing on master travis build

### ISSUE THREAD

**Issue by gurungrahul2** [aashutoshrathi/git-profiler-bot#24]
Tests were passing on PR #18 but failed on master, maybe problem is not in tests but dep used by tests (not sure) as sometimes they pass and sometimes just hiccup. https://travis-ci.org/aashutoshrathi/git-profiler-bot

**Comment by aashutoshrathi** [comment]
Tests require internet, since it depends upon status received from web

**Comment by gurungrahul2** [comment]
@aashutoshrathi so we are gonna leave it like that?

**Comment by aashutoshrathi** [comment]
Send more PRs.
