### ISSUE TITLE
creation of serverless.env.yml is not successful

### ISSUE THREAD

**Issue by gurungrahul2** [aashutoshrathi/git-profiler-bot#28]
Travis hangs because we have to press enter after ``cat >serverless.env.yml`` command, https://travis-ci.org/aashutoshrathi/git-profiler-bot/jobs/472424277 thus leading to build failure, :( ,find better travis friendly alternative to add this file.

**Comment by aashutoshrathi** [comment]
```sh
echo "some file content" > /path/to/outputfile
```

I think this should work fine

**Comment by gurungrahul2** [comment]
@gurungrahul2 actually echo doesn't support newline character, I think printf is more good for this purpose, sending a PR.
